import { Geist, Geist_Mono, Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CTA from "@/components/CTA";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const urbanist =Urbanist({subsets:['latin'], weight:['400','500','600','700','800','900']});
export const metadata = {
  title: "Maya Properties",
  description: "Generated by Maya Properties",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} antialiased flex flex-col bg-black text-white`}
      >
        <Navbar/>
       <div className="mt-[15%] md:mt-[5%]">{children}</div>
       <CTA/>
       <Footer/>
      </body>
    </html>
  );
}
